[package]
name = "seg"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
tempfile = "3.13.0"
tokio = { version = "1.40.0", features = ["full"] }
